# icecast configurations
host = "10.211.55.2"
port = 8000
password = "hackme"

frisky_mp3_high_mount = "frisky_mp3_hi"
# frisky_aac_high_mount = "frisky_aac_hi"
# frisky_aac_low_mount = "frisky_aac_low"

chill_mount = "friskychill_mp3_high"
deep_mount = "friskydeep_aachi"

frisky_pls_path="/home/parallels/Desktop/radio/frisky.m3u"
chill_pls_path="/home/parallels/Desktop/radio/chill.m3u"
deep_pls_path="/home/parallels/Desktop/radio/deep.m3u"
